### ISSUE TITLE
run it with an usb camera?

### ISSUE THREAD

**Issue by tulbureandreit** [amirhosseinh77/JetsonYolo#1]
Hello, how can I run it with an usb camera plugged in the Jetson Nano?
With this setup I get the cv2.error that says that no frames are supplied?
I tried to modify the sensor-id but to no success.

Thanks!

**Comment by arbit3rr** [comment]
Hi there, USB cameras are simply detected by the OS and most of the times, there is no need for extra drivers. But before that check the camera with this command : `ls /dev/video0`

If everything is ok and camera is available, just change videoCapture object in the main code and you don’t need the pipeline stuff.
`cap = cv2.VideoCapture(0)`

**Comment by tulbureandreit** [comment]
But isn`t G streamer better suited for Embedded devices? Wouldn`t Videocapture(0) be too laggy?

**Comment by arbit3rr** [comment]
Yes, I get it but I have not used it that way. 
I can’t help right now but you probably find it online.

**Comment by tulbureandreit** [comment]
If any body else is interested: this solved it

„if USB_GSTREAMER:
        gst_str = ('v4l2src device=/dev/video0 ! '
                   'video/x-raw, width=(640, height=480 ! '
                   'videoconvert ! appsink')
        return cv2.VideoCapture(gst_str, cv2.CAP_GSTREAMER)
    else:
        return cv2.VideoCapture(dev) 
18)	”

**Comment by tulbureandreit** [comment]
@amirhosseinh77 any idea how to live stream the output ?

**Comment by arbit3rr** [comment]
Thanks for sharing that. I don't have much experience in streaming but this repository was helpful for me:
https://github.com/NakulLakhotia/Live-Streaming-using-OpenCV-Flask

**Comment by tulbureandreit** [comment]
Thank you!

I also saw that https://github.com/jeffbass/imagezmq may be useful!

**Comment by arbit3rr** [comment]
Nice, thanks!
