### ISSUE TITLE
cv2.error: OpenCV(4.1.1)

### ISSUE THREAD

**Issue by yahya200** [amirhosseinh77/JetsonYolo#2]
hi,
 i am trying to run yolov5 on jetson nano 2gb . I use 
waveshare IMX219-160 Camera 
 jetpack 4.6
opencv (4.1.1)
torch (1.8.0)
torchvision(0.9.0)
i get this error :
File "JetsonYolo.py", line 69, in <module>
    cv2.imshow("CSI Camera", frame)
cv2.error: OpenCV(4.1.1) /home/nvidia/host/build_opencv/nv_opencv/modules/highgui/src/window.cpp:352: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'

any help?

**Comment by arbit3rr** [comment]
Hi there,
It seems like the output frame is empty. Print your frame to see if it's None or not.
If it's None:
1) make sure your camera is properly connected and recognized by the board. (ls /dev/video0)
2) If it's not recognized, search for the proper driver (Check out Arducam website)
These should work, but if you still have a problem, check out Yolo output to see if it's working fine or not.

**Comment by yahya200** [comment]
hi amirhosseinh77,
thanks for your reply.
i test the waveshare IMX219-160 camera through this command :
DISPLAY=:0.0 gst-launch-1.0 nvarguscamerasrc ! 'video/x-raw(memory:NVMM), width=3280, height=2464, format=(string)NV12, framerate=(fraction)20/1' ! nvoverlaysink -e
and it works fine. even throgh (ls /dev/video0) it is recognized by the board.
for your information when i run python3 JetsonYolo.py for first time the camera detects object for only one second then it stops > the following is the results and the problem: 
![Screenshot from 2021-12-06 20-55-08](https://user-images.githubusercontent.com/15201069/144898688-ea2c2b6b-0fab-4a8b-a3c9-283ab553f300.png)
 python3 JetsonYolo.py
/home/jetson/JetsonYolo/utils/plots.py:24: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'TkAgg' by the following code:
  File "JetsonYolo.py", line 3, in <module>
    from elements.yolo import OBJ_DETECTION
  File "/home/jetson/JetsonYolo/elements/yolo.py", line 4, in <module>
    from models.experimental import attempt_load
  File "/home/jetson/JetsonYolo/models/experimental.py", line 7, in <module>
    from models.common import Conv, DWConv
  File "/home/jetson/JetsonYolo/models/common.py", line 15, in <module>
    from utils.datasets import letterbox
  File "/home/jetson/JetsonYolo/utils/datasets.py", line 24, in <module>
    from utils.general import check_requirements, xyxy2xywh, xywh2xyxy, xywhn2xyxy, xyn2xy, segment2box, segments2boxes, \
  File "/home/jetson/JetsonYolo/utils/general.py", line 25, in <module>
    from utils.metrics import fitness
  File "/home/jetson/JetsonYolo/utils/metrics.py", line 5, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 72, in <module>
    from matplotlib.backends import pylab_setup
  File "/usr/lib/python3/dist-packages/matplotlib/backends/__init__.py", line 14, in <module>
    line for line in traceback.format_stack()


  matplotlib.use('Agg')  # for writing to files only
nvarguscamerasrc ! video/x-raw(memory:NVMM), width=(int)640, height=(int)480, format=(string)NV12, framerate=(fraction)6/1 ! nvvidconv flip-method=0 ! video/x-raw, width=(int)640, height=(int)480, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink
GST_ARGUS: Creating output stream
CONSUMER: Waiting until producer is connected...
GST_ARGUS: Available Sensor modes :
GST_ARGUS: 3264 x 2464 FR = 21.000000 fps Duration = 47619048 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 3264 x 1848 FR = 28.000001 fps Duration = 35714284 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 1920 x 1080 FR = 29.999999 fps Duration = 33333334 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 1640 x 1232 FR = 29.999999 fps Duration = 33333334 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 1280 x 720 FR = 59.999999 fps Duration = 16666667 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 1280 x 720 FR = 120.000005 fps Duration = 8333333 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: Running with following settings:
   Camera index = 0 
   Camera mode  = 5 
   Output Stream W = 1280 H = 720 
   seconds to Run    = 0 
   Frame Rate = 120.000005 
GST_ARGUS: Setup Complete, Starting captures for 0 seconds
GST_ARGUS: Starting repeat capture requests.
CONSUMER: Producer has connected; continuing.
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (933) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
CONSUMER: Done Success
Traceback (most recent call last):
  File "JetsonYolo.py", line 68, in <module>
    cv2.imshow("CSI Camera", frame)
cv2.error: OpenCV(4.1.1) /home/nvidia/host/build_opencv/nv_opencv/modules/highgui/src/window.cpp:352: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'

GST_ARGUS: Cleaning up
(Argus) Error Timeout:  (propagating from src/rpc/socket/client/ClientSocketManager.cpp, function send(), line 137)
(Argus) Error Timeout:  (propagating from src/rpc/socket/client/SocketClientDispatch.cpp, function dispatch(), line 91)
(Argus) Error Timeout:  (propagating from src/rpc/socket/client/ClientSocketManager.cpp, function send(), line 137)
(Argus) Error Timeout:  (propagating from src/rpc/socket/client/SocketClientDispatch.cpp, function dispatch(), line 91)
GST_ARGUS: Done Success
(Argus) Error InvalidState: Argus client is exiting with 2 outstanding client threads (in src/rpc/socket/client/ClientSocketManager.cpp, function recvThreadCore(), line 357)

**Comment by hayder200** [comment]
Hi yahya200
Did you try using:

import matplotlib
matplotlib.use('Agg')

**Comment by arbit3rr** [comment]
This 'imshow' error from OpenCV happens when the frame is empty in this line of code.
```python
cv2.imshow("CSI Camera", frame)
```
It is because ```cap.read()``` fails to get a new frame and skips the detection process to ```imshow``` line.
but weirdly, you receive the first frame from the camera but not the others.
I didn't have the same problem on my 4GB jetson nano and it might be because of ram.
try running the code without the   # detection process and # plotting sections and check the GStreamer code to see if it is ok with just getting frames.
I used the code on https://github.com/JetsonHacksNano/CSI-Camera for GStreamer and it may have a solution for your problem.

I hope you find a solution to that.
