### ISSUE TITLE
Runtimeerror: the size of tensor a (40) must match the size of tensor b (84) at Non singleton dimension 3

### ISSUE THREAD

**Issue by sachMK2** [amirhosseinh77/JetsonYolo#3]
Hello, I use JetsonYolo with yolov5s.pt V.5. It works great.

But when I try to use my custom yolov5 training. I get the following error: Runtimeerror: the size of tensor a (40) must match the size of tensor b (84) at Non singleton dimension 3.

Here is how I train it on my pc.

python3 train.py --data data/dataset/data.yaml --weights yolov5s.pt --cfg yolov5s.yaml --epochs 300 --img 640

I have modified in the JetsonYolo folder the object classes in yoloV5s.yaml and in the code JetsonYolo.py

Do you have a solution to my problem?

**Comment by arbit3rr** [comment]
Hi there,
I think your error comes from changes in the model of yolov5.
There are 2 folders (models & utils) that are from the yolov5 repository and their new models may be incompatible with old ones.
 So, updating these 2 folders might fix your problem.

**Comment by sachMK2** [comment]
Hi, thank you so much, it's working
