### ISSUE TITLE
Camera Quality

### ISSUE THREAD

**Issue by Dhruv-Chamaria** [amirhosseinh77/JetsonYolo#4]
Hello Amirhosseinh. I have got an issue with the quality of the camera that is been used to get blue images. Can you provide a sample video from the camera that you used in the process?

**Comment by arbit3rr** [comment]
Hi there,
Unfortunately, I don't have access to the camera or the board but as you can see from the image of Readme, I didn't have such a problem.
If you want to run the code using a video file, some changes in line 48 of JertsonYolo.py are needed.
I use OpenCV to read camera frames, so just change:
        cap = cv2.VideoCapture(gstreamer_pipeline(flip_method=0), cv2.CAP_GSTREAMER)
to:
        cap = cv2.VideoCapture('your_video.mp4')

This link is just another version of the code for person detection and might be helpful.
https://github.com/NEFTeam/Traffic-Law-Enforcement/blob/main/Jetson/London_Person_Detection.py
