### ISSUE TITLE
My own dataset is not working

### ISSUE THREAD

**Issue by fortunaLim** [amirhosseinh77/JetsonYolo#5]
Hello sir, thank for your video. 

I can run your code on my Jetson. 

I need to build with my own dataset so I modified Object_classes and path of yolov5s to best.pt(my own). 
But!!! It didn't work well bcz of "attributeerror can't get attribute 'sppf' on module 'models.common' from './yolov5/models/common.py" or "the size of tensor a must match the size of tensor b at non-singleton dimension 3"

so HOW should I do it for fix this error?

Please help me My captin!!!

**Comment by arbit3rr** [comment]
Hi there,
This error comes from changes in the Yolov5 repository.
The same issue is discussed here and I think this link can solve the problem: https://github.com/amirhosseinh77/JetsonYolo/issues/3

I copy the answer here as well.
"The error comes from changes in the model of yolov5.
There are 2 folders (models & utils) that are from the yolov5 repository and their new models may be incompatible with old ones. So, updating these 2 folders might fix your problem."

**Comment by fortunaLim** [comment]
Hello,
Thank you so much for your fast comment.
I tried your suggestion, but It also had error.

So I just replaced to webcam instead of CSI camera.
And then, I could find my wanted results.
It was so easy to use webcam.

Anyway, I am glad because of your solution.
thanks for your solution, I got brave for solving my problem!!!

**Comment by arbit3rr** [comment]
Great! 💯
