### ISSUE TITLE
camera Interface model

### ISSUE THREAD

**Issue by yin-qiyu** [amirhosseinh77/JetsonYolo#6]
Hi, is the camera interface usb or csi？

The yolo doesn't seem to support direct calls to the csi camera, so what function did you use？

thank you.

**Comment by arbit3rr** [comment]
Hi there, I'm using CSI as the camera interface. 
I used this https://github.com/JetsonHacksNano/CSI-Camera mentioned in the readme to get the frame as a NumPy array and then pass it to the model myself.

Check out the main script for more details: https://github.com/amirhosseinh77/JetsonYolo/blob/main/JetsonYolo.py

**Comment by yin-qiyu** [comment]
Thank you for the answer.I will try it

**Comment by yin-qiyu** [comment]
I installed gstream and called the camera according to the official routine, but the name cannot be displayed

![image](https://user-images.githubusercontent.com/71932767/154786653-73409f4d-fabe-4da8-878c-273c40fb4dbb.png)

I can't start the camera with a simple command either
![image](https://user-images.githubusercontent.com/71932767/154786973-b41c88f8-b111-4438-b283-b581cd7dd59c.png)

**Comment by arbit3rr** [comment]
If something's wrong with the camera, [the main repo](https://github.com/JetsonHacksNano/CSI-Camera) can help you better.
but I suggest commenting "detection" and "plotting" parts of [the code](https://github.com/amirhosseinh77/JetsonYolo/blob/main/JetsonYolo.py) (lines 54 - 66) and checking the camera output itself using openCV.

**Comment by yin-qiyu** [comment]
ok  thank you so much ,i have already run this demo  [the main repo](https://github.com/JetsonHacksNano/CSI-Camera),The reason for the investigation may be that there is a problem with my camera .i will buy an usb-camera to run your project, Thank you for your patient answer

**Comment by arbit3rr** [comment]
Aha, ok then.
You're welcome, good luck.
