### ISSUE TITLE
RuntimeError: The size of tensor a (40) must match the size of tensor b (56) at non-singleton dimension 3

### ISSUE THREAD

**Issue by Aitherqwq** [amirhosseinh77/JetsonYolo#9]
Seemed that the problem is from torch
![image](https://user-images.githubusercontent.com/30474517/167283846-96c18f89-7241-4d91-9df6-364a885e7df9.png)

**Comment by arbit3rr** [comment]
Hi, I believe you have the same problem as [issue 3](https://github.com/amirhosseinh77/JetsonYolo/issues/3).
You can either download an older version of the model from [this link](https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt), which still works or update the codes from main yolo repository.

![image](https://user-images.githubusercontent.com/56114938/167347878-85faf859-e523-4e49-b18c-05975a11403f.png)
